---

namespace: "tdworz"
name: "programming_environments"
version: 0.0.1

description: An Ansible collection to help with the installation and configuration of programming environments.

authors:
  - Tom "tdworz" Dworzanski <tom@dworzanski.com>

readme: README.md
license:
  - GPL-3.0-or-later

repository: https://github.com/tdworz/ansible-collection-programming_environments
issues: https://github.com/tdworz/ansible-collection-programming_environments/issues

tags:
  - programming
  - development
  - coding
  - ruby
  - go
  - golang

dependencies: {}
